### ISSUE TITLE
Resource pack groups

### ISSUE THREAD

**Issue by SamB440** [SamB440/ForcePack#30]
```yaml
groups:
  group1:
    exact-match: true
    list: # will only apply to servers with EXACT name: hub01, hub02, spawn01
    - hub01
    - hub02
    - spawn01
    # .. add ur ForcePack plugin pack url, hashes, and stuff here
  group2:
    exact-match: false
    list: # will apply to ALL servers with name CONTAINING keywords: hub or spawn (example: hub01, spawn03, spawn100000, hub10000)
    - hub
    - spawn
    # .. add ur ForcePack plugin pack url, hashes, and stuff here
```
