### ISSUE TITLE
[Suggestion] Option to send only 1 pack for version-specific resource pack

### ISSUE THREAD

**Issue by kolderz** [SamB440/ForcePack#88]
My server version is 1.18.2. 
When having multiple version-specific resource packs at login players are still being sent the fallback resource pack which causes an error when loading with the client version that doesn't support it.
It would be fixed if the plugin only sent the version-specific pack and not the fallback pack at the same time.

Example current config.
``` 
packs:
    all:
      urls: ["https://example.com/files/Pack1.zip"]
      generate-hash: false
      hashes: ["118AFFFC54CDCD308702F81BA24E03223F15FE5F"]
    42:
      urls: ["https://example.com/files/Pack2.zip"]
      generate-hash: false
      hashes: ["118AFFFC54CDCD308702F81BA24E03223F15FE5F"]
    46:
      urls: ["https://example.com/files/Pack3.zip"]
      generate-hash: false
      hashes: ["118AFFFC54CDCD308702F81BA24E03223F15FE5F"]
```

With the config above when logging in using 1.21.4 I got sent 2 packs the fallback + version-specific resource pack. For some reason, it loads the fallback pack first and that caused an error because the 1.21.4 client can't load the fallback pack which made for the lower version.
